### ISSUE TITLE
Add delete DNS record

### ISSUE THREAD

**Issue by Alnaggar94** [tech-otaku/cloudflare-dns#1]
Hello, This script is really awesome, I wish it has the delete function to delete DNS records, I understand that to delete a record you have to pass the record id, and this is the issue, I'm not a coder just started learning and I was thinking if someone can add this function to this script may be by list the DNS records, filter for the ID and pass that into the delete call?

**Comment by tech-otaku** [comment]
Thank you @Alnaggar94 

I shied away from adding a delete function because of the possibility of two or more DNS records having the same `[-t TYPE]` and `[-n NAME]` as detailed in the _Limitations_ section of the [README](https://github.com/tech-otaku/cloudflare-dns#readme). So while it's simple enough to get a DNS record's ID, the script would need to ensure it's the one you intend to delete. Your idea of listing matches and prompting the user to choose is worth pursuing. 

When I have time, I'll take a look at adding a delete function.

**Comment by Alnaggar94** [comment]
@tech-otaku Thank you so much for your time. You are a great man. This script really helped me, and I like the way you organized it helped me a lot. I will be waiting until you make it. I wish you all the luck. 🌹

**Comment by tech-otaku** [comment]
Added the ability to delete a DNS record. See the updated [README ](https://github.com/tech-otaku/cloudflare-dns#readme) for details or `./cf-dns.sh -h`
