### ISSUE TITLE
Don't wait for user input

### ISSUE THREAD

**Issue by LeeWiu** [tech-otaku/cloudflare-dns#4]
Hi, this script worked fine but after this lines of codes was added, my script is waiting to confirm manually and I can't do that because it's running automatically on cron job, how can be always confirmed by default? I added 1, -a, or -A at the end of line but no go
`/etc/dns/cf-dns.sh -d example com -t AAAA -n mail -c $ipv6 -l 300 -x n 1 -a -A`

```                while true; do
                    read -p "Type $(for((x=1;x<=$i;++x)); do printf "'%s', " $x; done | rev | cut -c3- | sed 's/ ,/ ro /' | rev) to update an existing record, 'A' to add a new record or 'Q' to quit without changes and then press enter: " ANSWER
                    case $ANSWER in
                        [1-$i]) 
                            DNS_ID=$(sed -n $ANSWER'p' < $TMPFILE | cut -d ',' -f1 | cut -d ':' -f2); 
                            break;;
                        [aA])
                            unset DNS_ID; 
                            break;;
                        [qQ]) 
                            exit
                            ;;
                        *) 
    #                        echo "Please enter a valid option."
                            ;;
                    esac
                done```

**Comment by tech-otaku** [comment]
@TeHashX 

User interaction is required because of the way the script finds matching DNS records. See [How the Script Works](https://github.com/tech-otaku/cloudflare-dns#how-the-script-works). In short, when using the script to add a new DNS record or update an existing DNS record the script may be unsure if it needs to add or update.

A possible work-around is to have 2 cron jobs. The first to delete an existing DNS record  rather than update it (`-Z` for delete, `-a` to suppress the prompt asking to confirm deletion):

`/etc/dns/cf-dns.sh -d example com -t AAAA -n mail -Z -a`

The second to add a new DNS record:

`/etc/dns/cf-dns.sh -d example com -t AAAA -n mail -c $ipv6 -l 300 -x n`

Regards, Steve.

**Comment by wpresident** [comment]
@TeHashX use [yes](https://github.com/tech-otaku/cloudflare-dns/issues/7#issuecomment-1958841566)
https://github.com/tech-otaku/cloudflare-dns/issues/7#issuecomment-1958841566
